### ISSUE TITLE
Mention what platforms are supported in the readme?

### ISSUE THREAD

**Issue by kellpossible** [almindor/texel#1]
Tried building on windows, but it looks like termion dependency doesn't build on Windows?

```
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.4\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
```

**Comment by almindor** [comment]
Yes it seems Termion doesn't support Windows (see https://docs.rs/termion/1.5.4/termion/)

I actually thought it might but didn't test yet. I do plan to get crossterm supported as a separate tty backend at some point but it'll require a bit more refactoring.

**Comment by almindor** [comment]
https://github.com/almindor/texel/commit/2afb8bf5fba0226a7c154e91b321d789572fb92e fixes the README issue
